### ISSUE TITLE
Bug in matchpattern

### ISSUE THREAD

**Issue by Cthutu** [kokke/tiny-regex-c#10]
In the matchpattern function you pass `&pattern[2]` to matchStar and matchPlus.  This should be `&pattern[1]`.

**Comment by kokke** [comment]
Hi @Cthutu and thanks for reading my code :)

I don't think you are correct on this point, since if I apply this change, the test suite starts failing catastrophically.

Have you accounted any errors since you believe this to be a bug?

**Comment by Cthutu** [comment]
Sorry - I think you're right.  I expected "\\S*" to fail on "\t \n", but of course '*' matches to 0 :)  Sorry for wasting your time.

**Comment by Cthutu** [comment]
I've corporated your code into my C libraries and add hexadecimal matching with \x and \X.  Thanks for writing this.  It's given me a head start.

**Comment by kokke** [comment]
No problem, always happy to hear about uses of the code.
I'm looking forward to reading your implementation :)

Season's greetings
