### ISSUE TITLE
Can you support "Match - Search" feature?

### ISSUE THREAD

**Issue by 4kzeng** [kokke/tiny-regex-c#11]
example:  
    src text:   hello,  ac97!
    char* p  = re_search(src,  "^.+,/s?+ac(/d/d)");
   if( p != NULL )
       printf("Number is %c%c\n", *p, *(p+1));

**Comment by kokke** [comment]
Hi @4kzeng and thank you for taking an interest in this project :)

Unfortunately the current design does not support capturing groups at the moment, so what you are asking is currently not supported.
