### ISSUE TITLE
Can I set the number of characters for numbers?

### ISSUE THREAD

**Issue by Avlaak** [kokke/tiny-regex-c#12]
Can i set the number of characters for numbers (from 1 to 2), for example for this format "00:00:00"? 
The following pattern does not work: "\\d\\d?:\\d\\d?:\\d\\d?". Where could I make a mistake?

**Comment by kokke** [comment]
Hi @Avlaak :)

>Can i set the number of characters for numbers (from 1 to 2)

The best way I can think of, would be to use \d\d? like you are suggesting.

You should be able to match `"00:00:00"` using the pattern `\d\d?:\d\d?:\d\d?`.


>Where could I make a mistake?

Remember that you need to escape the backslash `\` when coding C, so the pattern `\d\d?` becomes `\\d\\d?`. Like this for instance: 
```C
char* pattern = "\\d\\d?"; /* <-- note the escaped-backslashes */
```

Could this be the problem?



I testing the pattern by adding the following test cases to [test1.c](https://github.com/kokke/tiny-regex-c/blob/master/tests/test1.c) - and they all succeed :

```C
{ OK,  "\\d\\d?:\\d\\d?:\\d\\d?",   "0:0:0"   },
{ OK,  "\\d\\d?:\\d\\d?:\\d\\d?",   "0:00:0"   },
{ OK,  "\\d\\d?:\\d\\d?:\\d\\d?",   "0:0:00"   },
{ OK,  "\\d\\d?:\\d\\d?:\\d\\d?",   "00:0:0"  },
{ OK,  "\\d\\d?:\\d\\d?:\\d\\d?",   "00:00:0"  },
{ OK,  "\\d\\d?:\\d\\d?:\\d\\d?",   "00:0:00"  },
{ OK,  "\\d\\d?:\\d\\d?:\\d\\d?",   "0:00:00"  },
{ OK,  "\\d\\d?:\\d\\d?:\\d\\d?",   "00:00:00" },
```

**Comment by Avlaak** [comment]
Hi, I also added following test cases to [test1.c](https://github.com/kokke/tiny-regex-c/blob/master/tests/test1.c) and I got the result "48/54 tests succeeded". 

`
{ NOK,  "\\d\\d?:\\d\\d?:\\d\\d?",  "0s:00:00" },
{ NOK,  "\\d\\d?:\\d\\d?:\\d\\d?",  "0s:00:00" },
`
`  { NOK,  "\\d\\d?:\\d\\d?:\\d\\d?",  "0s:00:00" },`
`  { NOK,  "\\d\\d?:\\d\\d?:\\d\\d?",  "000:00" },`
`  { NOK,  "\\d\\d?:\\d\\d?:\\d\\d?",  "00:0000" },`
`  { NOK,  "\\d\\d?:\\d\\d?:\\d\\d?",  "100:00:00" },`
`  { NOK,  "\\d\\d?:\\d\\d?:\\d\\d?",  "00:100:00" },`
`  { NOK,  "\\d\\d?:\\d\\d?:\\d\\d?",  "00:00:100" },`

**Comment by kokke** [comment]
Hi @Avlaak - it looks like you have found a bug in the non-greedy quantifier `?`.

I did some testing, and it looks like it is the non-greedy quantifier that causes the pattern to match too broadly.

I will keep this issue open, label it as a bug and add a note in the TODO-list in the README, that it needs to be looked at.

**Comment by kokke** [comment]
I've uploaded some changes that should fix your problem - at least the ones we've identified in this issue :)

Let me know if the last commits fix your problem.

**Comment by Avlaak** [comment]
Hi @kokke, unfortunately the problem has remained, try to test the pattern.
```  { NOK,  "\\d\\d?:\\d\\d?:\\d\\d?",   "a:0"            },```

**Comment by kokke** [comment]
Hmm I need to think a bit deeper about this then.

It looks like the bug is still in the code handling the question-mark.
