### ISSUE TITLE
Python version shenanigans

### ISSUE THREAD

**Issue by roflcopter4** [kokke/tiny-regex-c#13]
This is about the tiniest issue ever, but I figured I'd ask anyway. Many platforms (certainly at least ArchLinux and Gentoo) these days use python3 as the standard python implementation. The scripts included are all definitely python2 code and thus the tests fail immediately. It took approximately 3 seconds to type `$ perl -pi -e 's/python/python2/g' Makefile scripts/*.py` to fix it completely, but it might be nice if you'd incorporate this into the source itself.

Again, not really much of an issue, but worth pointing out anyway.

**Comment by kokke** [comment]
Hi @roflcopter4 and thanks for checking out the project :) I like the idea to be python3 compatible. Would you suggested fix be backward-compatible with machines without python3 installed?

If so, I suggest you make a PR and I'd gladly accept it :) ?

**Comment by kokke** [comment]
Closing because I merged your PR https://github.com/kokke/tiny-regex-c/pull/14 :) 

Thanks again @roflcopter4
