### ISSUE TITLE
Problem into ".?" matching.

### ISSUE THREAD

**Issue by TermoSINteZ** [kokke/tiny-regex-c#15]
https://github.com/kokke/tiny-regex-c/blob/bf9b2f0c5e91dd12e1fea8cbc7ae7a6193e7b4ed/re.c#L382

Hello kokke! You have very good parser. But some improvement will be good inserting. 
So 
Checked string : "real_bar" with regexp ".?ba.*" - you have match into 0 index (correct result 4 index)
Checked string : "real_foo" with regexp ".?ba.*" - you have match into 0 index (correct result -1 (or nothing match)

If necessary - I can give you an example of a solution

**Comment by TermoSINteZ** [comment]
You can see possible solution into my fork:
https://github.com/TermoSINteZ/tiny-regex-c

**Comment by kokke** [comment]
Hi @TermoSINteZ and thank you for the kind words :)

Great job on fixing the bugs! I will copy the code right away - unless you want to make a PR and get on the contributor list? I will gladly accept a PR.

**Comment by TermoSINteZ** [comment]
Thanks
