### ISSUE TITLE
Could you submit a version support "{}" ?

### ISSUE THREAD

**Issue by ShuHu2015** [kokke/tiny-regex-c#18]
for example "^28\d{15,16}$"

**Comment by kokke** [comment]
Hi @ShuHu2015 and thanks for your interest :)

Supporting curly-braces would require a radical change in the current design, so unfortunately no, that is not an option.

**Comment by ShuHu2015** [comment]
Thanks for your reply, do you know any regex lib support curly-braces?

**Comment by kokke** [comment]
Hi @ShuHu2015 

This library is popular: https://www.pcre.org/

**Comment by ShuHu2015** [comment]
pcre is a big project. It is too hard for me to port pcre to my embed system....

**Comment by kokke** [comment]
I don't know of other regex libraries suitable for embedded use.

**Comment by monolifed** [comment]
This is a good starting point to look for simple libraries:  
https://github.com/nothings/single_file_libs
  
This seem to support curly braces:  
https://github.com/ccxvii/minilibs/blob/master/regexp.c
This might support it one day:  
https://github.com/gingerBill/gb/blob/master/gb_regex.h
(I checked neither of them. So no idea about how they perform)

**Comment by kokke** [comment]
Hi @ShuHu2015 

@monolifed now has a branch of this library, that supports quantifiers / curly-braces as well :D

Available from: https://github.com/monolifed/tiny-regex-c/tree/quantifier
