### ISSUE TITLE
Feature Requests and Minor Code Comments

### ISSUE THREAD

**Issue by mattharrigan** [kokke/tiny-regex-c#2]
Hello.  First thank you for this library.  It has been very helpful.  Two small comments/questions on the code.  Note I am still learning C.

First [here](https://github.com/kokke/tiny-regex-c/blob/master/re.c#L107) I think ccl_bufidx could be initialized to 1, otherwise the first slot in the array is unused.  I might be missing something though.

Second, I don't understand why there is a union in the struct regex_t.  I think with padding it doesn't actually save any space for most architectures.  However it might be possible to keep an index for the array instead of the pointer to the position in the array, which could be a small data type, possible even just a char.

Finally two features would help me, and perhaps many others also.  First would be case insensitive matching.  The second would be to have dynamically allocated patterns, which would allow more than one pattern to be used in a program.  I realize either of those may not be in keeping with "tiny", so they may not be appropriate here.

Again thank you very much for this useful code.

**Comment by kokke** [comment]
Hi @mattharrigan and thank you for taking an interest in this project :)

First I'm sorry I've been so slow to respond. Your issue slipped my mind for quite some time...

I don't actually remember my reasoning for initializing the index to 1. Maybe that's also why I never got back to you in the first place.

The reason for the union is to be able to safely use the same piece of memory as both a char and a pointer. [Type punning](https://en.wikipedia.org/wiki/Type_punning) can invoke undefined behavior which leads to crazy bugs :)

Please check out #7 for dynamic allocation and a much more feature-packed fork of this project.
