### ISSUE TITLE
Match question mark fails?

### ISSUE THREAD

**Issue by tobermory** [kokke/tiny-regex-c#20]
If my pattern is X?Y and my text is 'Z' I would expect this to not match, but it appears that it is matching?  I think the logic in matchquestion is wrong.  Once the two tests in that routine fail, we pass through to a result of 1, which becomes the result of the overall matchpattern.  The remainder of the pattern isn't ever consulted.

Also, and this may be related, the pattern indices in the recursive and iterative matchpattern routines don't match.  I'm not saying that they should, just noting their differences.

**Comment by kokke** [comment]
Hi @tobermory - thanks for reporting this issue.

I agree, "X?Z" should not match "Z". 
This is a bug in the question-mark matching code, but I am not quite sure how to fix it.

For now, I will add your failing test-case to the list of hand-picked tests in the test-suite.
At least that makes it visible that something is failing in that area.
That also means I can track when it gets fixed -- that's a start.

If you have time to look at it, feel free to submit a Pull Request fixing the issue.


Regarding the index-difference between the iterative and the recursive version -- that looks suspicious, I agree.

**Comment by monolifed** [comment]
```C
static int matchquestion(regex_t p, regex_t* pattern, const char* text)
{
  // end of pattern
  if(p.type == UNUSED)
    return 1;
  // already matches without optional part
  if (matchpattern(pattern, text))
      return 1;
  // optional part matches; advance
  if (*text && matchone(p, *text))
    return matchpattern(pattern, text + 1);
  return 0;
}
```
I hope this works better than the last time
(It still fails some of the `make test` tests)

**Comment by kokke** [comment]
Hi @monolifed and thanks for contributing :)

I am not near a computer now, but I will review your suggested changes and try to see if I can make sense of the failing cases.

**Comment by kokke** [comment]
Hey @monolifed - I just had a few minutes to look at this again.
I think I agree with your diagnosis of the first failing case:

>   pattern '\d+\w?\D\d':                FAIL : doesn't match '18' as expected [0x31, 0x38].

'18' does indeed not match `\d+\w?\D\d`, so something is wrong with the input data being generated.
Should be possible to find the problem and fix that in the Python code.

Haven't had the time to look at the second failing case yet, but your explanation sounds plausible. Failing to handle the backspace as a character-class `[\]` would explain the failure.

I will try to review ASAP, but I may not have the time before the end of this week.

I suggest you make a pull request containing the changes, which I will then merge.
That way, you  get proper attribution for the fix :)

**Comment by monolifed** [comment]
```diff
        /* Copy characters inside [..] to buffer */
        while (    (pattern[++i] != ']')
                && (pattern[i]   != '\0')) /* Missing ] */
        {
          if (ccl_bufidx >= MAX_CHAR_CLASS_LEN) {
              //fputs("exceeded internal buffer!\n", stderr);
              return 0;
          }
+++          if (pattern[i] == '\\')
+++            ccl_buf[ccl_bufidx++] = pattern[i++];
          ccl_buf[ccl_bufidx++] = pattern[i];
        }
```
this seems to fix unhandled `\]` in char-class but there is a possibility of overflow
(ccl_bufidx == MAX_CHAR_CLASS_LEN - 1 && pattern[i] == '\\')

**Comment by kokke** [comment]
@monolifed 

This should be closed no?
