### ISSUE TITLE
End of match

### ISSUE THREAD

**Issue by jkhax0r** [kokke/tiny-regex-c#24]
The re_match() routine returns the first character of the match.  Is there an easy way to return the last matching character of the string?  I'm trying to copy out only the resulting matching string but can't think of an easy way.  

Great library by the way!

**Comment by monolifed** [comment]
I did it by returning text or NULL in matchpattern, it should point to the end of match.  
https://github.com/monolifed/tiny-regex-c/blob/master/re.c#L371

**Comment by kokke** [comment]
The length of the match can now be returned as per #36
