### ISSUE TITLE
Simple Date format not matched

### ISSUE THREAD

**Issue by gjois** [kokke/tiny-regex-c#29]
Please check this site for example: https://regex101.com/r/ZqMTdp/1
the same input to your sample program is not giving the match. Am I missing something?
I'm really a newbie in regexp.

**Comment by kokke** [comment]
Hi @gjois and thanks for the question

Currently, quantifier-operators are unsupported, and your regular expression is using those operators.

In this regular expression: `\d{4}-\d{2}-\d{2}` <-- the quantifiers are {4}, {2}  and {2}. 

You should be able to achieve the same result with this pattern: `\d\d\d\d-\d\d-\d\d`.

**Comment by kokke** [comment]
This fork has support for quantifiers: https://github.com/kokke/tiny-regex-c/pull/23
