### ISSUE TITLE
Thread safety

### ISSUE THREAD

**Issue by ogamespec** [kokke/tiny-regex-c#31]
https://github.com/kokke/tiny-regex-c/blob/d3058f271f7a06ff298dff0a6a9a1e0753a5fa17/re.c#L111

Looks like its non thread safe (non-reentrant)

**Comment by kokke** [comment]
Hi @ogamespec and thanks for your comment :)

Your observation is totally correct: this code is not reentrant. 

The code is targeted towards embedded and resource-constrained targets, where dynamic allocation is verboten and binary size matters.

Some of the forks of this project vastly expands functionality and I also believes thread-safety is implemented in some of them. If this is a requirement for your use case, I would advise you to check out some of the forks, in particular the one by @monolifed :)

An easy fix/hack would be to either 1) pass the memory from the caller, or 2) place a lock/mutex inside the compile function.

**Comment by ogamespec** [comment]
Resolved)
