### ISSUE TITLE
feature request: lookahead and lookbehind

### ISSUE THREAD

**Issue by theo-dep** [kokke/tiny-regex-c#34]
feature request: https://www.regular-expressions.info/lookaround.html

**Comment by kokke** [comment]
Hi @theo-dep - how did the lookahead/behind work out for you? Did you ever implement this?

As mentioned in #38 I am considering re-implementing the data-model, but it would require some rewriting.. I don't think I will be adding any feature in the near future. I have a lot on the program privately that limits my time available for it.

**Comment by theo-dep** [comment]
Hi, it is a long time ago, I do not remember if that code work 😅 and if I finally used it.
Do not worry, I am in other project now, I wish to thank you for the future work!
