### ISSUE TITLE
Needs #ifdef __cplusplus

### ISSUE THREAD

**Issue by blitz-research** [kokke/tiny-regex-c#4]
Hi,

Nice little library!

To make it usable with c++, you need to add this:

```
#ifdef _cplusplus
extern "C"{
#endif
```
...before the definitions in the header file, and this...

```
#ifdef _cplusplus
}
#endif
```

...after.

Otherwise, c++ will assume symbols like re_match etc are c++ symbols and you'll get link errors. More info here:

https://stackoverflow.com/questions/3789340/combining-c-and-c-how-does-ifdef-cplusplus-work

**Comment by kokke** [comment]
Oh, I haven't mixed C and C++ in a few years, so I hadn't been aware of that issue.
Yeah I would have to do that to avoid trouble with the name mangling right? 
Or could I require the user to know that the library is written in C, and then do one of two:

1) either put it in a C++ header with the `extern C { ... }` tag wrapped around the contents
2) or put the `extern`-stuff before `#include`'ing the file right?

What do you think? Would any of those options work for C++? I'm online from my phone right now, so no easy way to test it at the moment..

**Comment by blitz-research** [comment]
Just add the #ifdefs to the existing re.h file. C compilers will ignore them because __cplusplus wont be defined, and c++ compilers will know not to mangle the names because of the extern"C".

Here's my re.h which builds fine with my c++ code. Would've done a pull request except I suck at git.

```
/*
 *
 * Mini regex-module inspired by Rob Pike's regex code described in:
 *
 * http://www.cs.princeton.edu/courses/archive/spr09/cos333/beautiful.html
 *
 *
 *
 * Supports:
 * ---------
 *   '.'        Dot, matches any character
 *   '^'        Start anchor, matches beginning of string
 *   '$'        End anchor, matches end of string
 *   '*'        Asterisk, match zero or more (greedy)
 *   '+'        Plus, match one or more (greedy)
 *   '?'        Question, match zero or one (non-greedy)
 *   '[abc]'    Character class, match if one of {'a', 'b', 'c'}
 *   '[^abc]'   Inverted class, match if NOT one of {'a', 'b', 'c'} -- NOTE: feature is currently broken!
 *   '[a-zA-Z]' Character ranges, the character set of the ranges { a-z | A-Z }
 *   '\s'       Whitespace, \t \f \r \n \v and spaces
 *   '\S'       Non-whitespace
 *   '\w'       Alphanumeric, [a-zA-Z0-9_]
 *   '\W'       Non-alphanumeric
 *   '\d'       Digits, [0-9]
 *   '\D'       Non-digits
 *
 *
 */

#ifdef __cplusplus
extern "C"{
#endif

/* Typedef'd pointer to get abstract datatype. */
typedef struct regex_t* re_t;


/* Compile regex string pattern to a regex_t-array. */
re_t re_compile(const char* pattern);


/* Find matches of the compiled pattern inside text. */
int  re_matchp(re_t pattern, const char* text);


/* Find matches of the txt pattern inside text (will compile automatically first). */
int  re_match(const char* pattern, const char* text);

#ifdef __cplusplus
}
#endif
```

**Comment by blitz-research** [comment]
...might also want to add an include guard, but it's such a small file it probably wouldn't be any faster!

**Comment by kokke** [comment]
Yeah that is just the best solution :)

I've added the `#ifdef`-guard in the header - try pulling
