### ISSUE TITLE
Prevent duplicate include  errors

### ISSUE THREAD

**Issue by skyformat99** [kokke/tiny-regex-c#43]
re.h file   
The header and the tail of the file are added separately。

#ifndef      __TINY_REGEX_C_
#define     __TINY_REGEX_C_

......................
...................
....................

#endif

**Comment by kokke** [comment]
Hi @skyformat99 and thanks for your interest 👍 

It’s a good idea and I agree that header include guards are needed.

**Comment by kokke** [comment]
Added in this commit: https://github.com/kokke/tiny-regex-c/commit/9d46276c48091a22ac4fa6472603fe4b17d483ce

**Comment by kokke** [comment]
Once again, thanks for pointing it out @skyformat99
