### ISSUE TITLE
I ported this to rust

### ISSUE THREAD

**Issue by gmorenz** [kokke/tiny-regex-c#57]
Hi,

Just thought I'd let you know that I ported this to rust for fun after seeing it on [lobste.rs](https://lobste.rs/s/xouda7/small_regex_implementation_c_less_than). The [repo is here](https://github.com/gmorenz/tiny-regex-rs). There are a few small changes in internals, but it's a reasonably direct port.

Thanks for making this cool little library :)

**Comment by kokke** [comment]
Hi @gmorenz and thanks for letting me know about your project :) I am not yet well versed in Rust, but I'll take a look.

I am currently using the Python re module as test oracle, which is kinda slow. It would be nice to have something faster like an implementation in Rust (yours?) - maybe just as an addition to Python. Would that be an fun project?

I noticed a ~20x increase in traffic on this project over the past two days and found a lot of it coming from reddit and lobste.rs :D
