### ISSUE TITLE
Migrate all test scripts to Python v3

### ISSUE THREAD

**Issue by rilysh** [kokke/tiny-regex-c#89]
Hello,

Currently, test scripts uses syntax and libraries from Python 2 but most GNU/Linux
distributions has remove Python 2 from their repository, making it harder
to get a Py2 binary unless compiling it from source. It'd be nice if you or
an individual migrate them to use Python 3. I'm more than happy to help if needed!

Thanks!

**Comment by kokke** [comment]
Hi @rilysh

I agree that would be nice. I don't have much time for FOSS contributions at the moment, but if you are willing to make some efforts I would be happy to accept the help.

If you're willing to undertake the migration effort, I suggest doing it somewhat like this:

- Open a branch (e.g. called ´python3-support` or similar) and make the work there
  That makes it easy to compare against the `main`-branch.
- You can make all work on a single branch or make branches for each major change (not sure that makes a lot of sense here)
- When you think you're finished, open a PR and let me review the changes.
  I assume the changes will be mostly mechanical and minor, as it's just a change from v2 -> v3 and not a rewrite of the functionality.
- I would also be willing to discuss the proposed changes in one or more issues before you implement them. Your choice.

Apologies beforehand if I'm a bit slow to react. I have a many irons in the fire 🔥🐝

**Comment by kokke** [comment]
Finally found time to do this :sweat_smile:
